tree-cutter: true

safe-mounts: true

chicken-shearing:
  enabled: true
  damage-per-shear: 1
  shear-without-shears: false

ladder-drop-down: false # Might be broken

minecart-block-placement: true

shave-snow-layers: true

better-silk-touch:
  enabled: true
  blocks:
  - GRASS_PATH
  - FROSTED_ICE
  - FARMLAND

better-compass:
  enabled: true
  # Set where the compass should point to
  # Possible values: north, east, south, west, spawnpoint, worldspawn, lastdeath, <x>/<z>
  point-to: spawnpoint

# Increase the amount of litters of mobs
# If a minimum is not defined it will assume 1, default max is 10
bigger-litters:
  enabled: true
  # Whether or not to give more exp depending on the size of the liter
  more-exp: true
  mobs:
    pig:
      min: 3
      max: 10
    rabbit:
      min: 3
      max: 7
    chicken:
      min: 2
      max: 5
    ocelot:
      min: 2
      max: 4
    wolf:
      max: 6

# Heal mobs (like golems) by clicking (or throwing with snowballs) with an item
heal-items:
  enabled: true
  mobs:
    snow-golem:
      snowball: 1.0
      snow_block: 9.0

door-knocking:
  enabled: true
  requires-sneaking: true
  knock-with-right-click: false
  sounds:
    iron_door_block: entity.zombie.attack_iron_door
    oak_door: entity.zombie.attack_wooden_door
    acacia_door: entity.zombie.attack_wooden_door
    birch_door: entity.zombie.attack_wooden_door
    jungle_door: entity.zombie.attack_wooden_door
    spruce_door: entity.zombie.attack_wooden_door
    dark_oak_door: entity.zombie.attack_wooden_door
    warped_door: entity.zombie.attack_wooden_door
    crimson_door: entity.zombie.attack_wooden_door
    oak_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    acacia_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    birch_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    jungle_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    spruce_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    dark_oak_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    warped_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5
    crimson_trapdoor:
      sound: entity.zombie.attack_wooden_door
      pitch: 1.5 
    iron_trapdoor:
      sound: entity.zombie.attack_iron_door
      pitch: 1.2
    oak_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    acacia_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    birch_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    jungle_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    spruce_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    dark_oak_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    warped_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2
    crimson_fence_gate:
      sound: entity.zombie.attack_wooden_door
      pitch: 2

more-sounds:
  enabled: true
  sounds:
    nether-portal-creation:
      sound: minecraft:entity.chicken.egg
      pitch: 0.5
    player-join:
      sound: minecraft:entity.chicken.egg
      pitch: 1
    item-despawn:
      sound: minecraft:entity.item.pickup
      pitch: 0.5
      volume: 0.5
